
# SERVER CONFIGS ------------------------------------

MAIN_IP: "126.126.0.10"
  # TLS Certificate must comply with this IP address.
PORT_BACK: 4040
PORT_FRONT: 5173
PORT_FRONT_DEV: 5174

UNREAL_IP: "127.0.0.1"
UNREAL_OSC_PORT: 8282
UNREAL_HTTP_PORT: 8080


# FACE TRACKER CONFIGS ------------------------------

MARGIN_X: 300
MARGIN_Y: 50
OFFSET_X: 0
OFFSET_Y: 0
DETECTION_CONFIDENCE: 0.5
TRACKING_CONFIDENCE: 0.5






