from modules import faceTracker

MARGIN_X, MARGIN_Y = 300, 50
OFFSET_X, OFFSET_Y = 0, 0
SHARPNESS = 100
CONTRAST = 100
DETECTION_CONFIDENCE = 0.5
TRACKING_CONFIDENCE = 0.5 



faceTracker.run_face_tracker(MARGIN_X, MARGIN_Y, OFFSET_X, OFFSET_Y, SHARPNESS, CONTRAST, DETECTION_CONFIDENCE, TRACKING_CONFIDENCE)
